version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "marketplace_db", "-U", "postgres" ]
      interval: 2s
      timeout: 1s
      retries: 20

volumes:
  db:
    driver: local
