name: Backend CD

on:
  workflow_run:
    workflows: [ "Backend CI" ]
    branches:
      - main
      - staging
      - production
    types:
      - completed

jobs:
  build_and_push_docker_image:
    name: Build and push docker image to AWS ECR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: ${{ github.event.workflow_run.head_branch == 'main' && 'develop' || github.event.workflow_run.head_branch }}
    concurrency:
      group: ${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Java setup
        uses: ./.github/actions/java-setup

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE }}

      - name: Retrieve parameters
        shell: bash
        run: |
          echo ECR_REPOSITORY_URI=$(aws ecr describe-repositories --query "repositories[?contains(@.repositoryName, 'indexerrepository') == \`true\`].repositoryUri" --output text) >> "$GITHUB_ENV"
          echo SHA_SHORT=$(git rev-parse --short HEAD) >> "$GITHUB_ENV"

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_REPOSITORY_URI }}

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.ECR_REPOSITORY_URI }}:latest
            ${{ env.ECR_REPOSITORY_URI }}:${{ env.SHA_SHORT }}
